### ISSUE TITLE
[QA] 홈,설정 디자인/기능QA

### ISSUE THREAD

**Issue by jayleeee** [Dayol-Studio/Dayol-iOS#216]
**<테스트 환경>**
기기 : iPhone 11 Pro
OS버전 : iOS 14.6
앱버전 : 1.0 (2021.808.1917)

**<상세 설명>**
- 우선 모바일만 진행하였음.

![QA_홈](https://user-images.githubusercontent.com/23701517/129211288-cb1fb732-8d9e-466a-a217-35fdf199a591.png)

**Comment by Sungmin-Joo** [comment]
요번 주말 중에 한방에 작업해두겠습니다

**Comment by Sungmin-Joo** [comment]
홈: https://github.com/Dayol-Studio/Dayol-iOS/pull/225

**Comment by Sungmin-Joo** [comment]
설정: https://github.com/Dayol-Studio/Dayol-iOS/pull/228 

3번은 화면 진입이 안되서.. 테스트 방법 공유받고 따로 작업해서 올리도록 하겠습니다.
