### ISSUE TITLE
[QA] 다이어리 뷰, 먼슬리 / 위클리 속지별 동작

### ISSUE THREAD

**Issue by jayleeee** [Dayol-Studio/Dayol-iOS#217]
<테스트 환경>
기기 : iPhone 11 Pro
OS버전 : iOS 14.6
앱버전 : 1.0 (2021.808.1917)

<상세 설명>

우선 모바일만 진행하였음.

![QA_다이어리먼슬리위클리](https://user-images.githubusercontent.com/23701517/128800149-b4827393-279a-41e1-8cd6-bf9d1b7dbb0d.png)

**Comment by ParkJongSang** [comment]
https://github.com/Dayol-Studio/Dayol-iOS/pull/215

 - 위클리, 데일리 속지 날짜 선택 화면 수정사항 반영, 페이퍼 Shadow 썸네일 반영
