### ISSUE TITLE
[QA] 데일리,나머지 기타 메모지들 

### ISSUE THREAD

**Issue by jayleeee** [Dayol-Studio/Dayol-iOS#218]
<테스트 환경>
기기 : iPhone 11 Pro
OS버전 : iOS 14.6
앱버전 : 1.0 (2021.808.1917)

<상세 설명>

우선 모바일만 진행하였음.
![데일리,기타메모](https://user-images.githubusercontent.com/23701517/128830001-7973be2c-4f2e-4955-9e86-ab8d765839c3.png)

**Comment by ParkJongSang** [comment]
https://github.com/Dayol-Studio/Dayol-iOS/pull/215

 - 데일리 헤더 관련 동작 반영
 - 데일리 사이즈 문제 수정
