### ISSUE TITLE
ApplePencil 관련 스펙 정리  

### ISSUE THREAD

**Issue by Sungmin-Joo** [Dayol-Studio/Dayol-iOS#23]
- [x] 기본 드로잉 기능 (메모, 그리기 등)  
  -> 필기감을 고려하여 직접 구현한다면 오랜 기간이 소모될 것 같음  
- [x] undo, redo  
  -> 드로잉 관련 태스크를 만들어 stack 구조로 관리
- [x] 지우개 기능 : 비트맵 지우기, 벡터 지우기  
    ->  벡터 지우기(객체 혹은 테스크 단위 지우기) 기능을 구현하기 위해서 알고리즘 구현 필요
- [ ] 올가미 기능   
    ->  드로잉 뿐만 아니라 스티커, 라벨이 같이 올가미로 묶여야 하는 스펙  
- [x] 컬러 파레트  
- [x] 드로잉 데이터 로드 및 저장.

**Comment by Sungmin-Joo** [comment]
## Introducing PecilKit
링크 - https://developer.apple.com/videos/play/wwdc2019/221/


## Summary
#
### About Apple Pencil
~패드 앱에 애플 펜슬이 더해져 좋은 경험을 만들어라 애플 펜슬은 엄청 좋으니까!~
- 애플 펜슬의 방위각, 고도, 압력 을 정확하게 받기 위해선 estimated value를 사용해야한다.  
-> 애플 펜슬에서 방위각, 고도, 압력을 정확하게 측정하기 어려운 케이스가 존재한다 (e.g. edge에서 부터 드로잉을 시작하는 경우) 이럴 경우를 대비해서 estimated value를 먼저 측정하고 후에 정확한 value를 통해 draw 정보를 업데이트 해주는 플로우로 구현
- 애플 펜슬의 위치를 정확하게 입력받기 위해선 predicted touch를 사용한다.  
-> 애플 펜슬은 240Hz의 입력속도를 자랑하지만, UIKit은 60Hz로 제한을 하기때문에 위 프로퍼티를 사용해야한다.  
[가이드](https://developer.apple.com/documentation/uikit/pencil_interactions/handling_input_from_apple_pencil)에 잘 설명이 되어있다.
- 드로잉 기능을 만드는 앱이라면, 레이턴시를 줄이기 위해 UI effects 나 블러 효과 등의 사용을 피하고, 투명 레이어와 같은 것을 피해라)  
- 이거 다 고려하면서 앱을 만들기엔 엄청 오랜 시간이 걸린다.

### About Pencil Kit
#### Pencil Kit의기능
- iOS 13.0 이상부터 지원한다.
- 개발에 많은 시간과 에너지를 아낄 수 있는 프레임워크이다.
- 세개의 라인만 추가하면 그림을 그릴 준비가 된다!  
- pencil kit 기능 소개  
-> 위에서 설명했던 estimated, predicted 관련 처리가 필요없이 최고의 필기감을 자랑한다.  
-> 컬러 파레트 기능을 제공한다.  
-> undo, redo 매니저를 따로 구현 할 필요가 없다.
-> 기본 올가미 툴이 존재한다.
-> 드로잉 데이터를 로드 및 저장을 할 수 있는 모델이 있다.   

#### Pencil Kit의 구조  
- PKCanvasView  
->draw 영역을 제공    
- PKDrawing  
->데이터 모델, stroke들을 capture한다. 그림들을 로드하거나 저장할 수 있는 데이터이다.
->value type이기때문에 백그라운드에서 수행 시 안전을 보장한다.
- PKTollPicker 
-> 기본으로 제공되는 도구 선택 UI  
- PKTool
->PKInkingTool, PKEraserTool, PKLassoTool 의 상위 클래스 
->순서대로 펜, 지우개, 올가미 기능을 한다.

## 앱 스펙과 비교해서 사용 시 문제 점  
>정리중...

**Comment by Sungmin-Joo** [comment]
![스크린샷 2021-01-23 오전 3 34 27](https://user-images.githubusercontent.com/46941349/105530938-eb719b00-5d2b-11eb-8678-563cb52b076c.png)

**Comment by jayleeee** [comment]
애플펜슬 부분은 우선순위 아래에 두고 일단 1번으로 진행하는게 어떰.
나중에 다른거 먼저 하고 2번도 다시 한번 검토해주고, 정안되면 2번은 Phase2에 가도 괜찮을듯. 

1. 기본 Pencil Kit으로 필기 기능은 제공해주고, 올가미툴 선택 시 '손으로 선택가능하다'고 알럿. + 손으로는 올가미툴 기능 모두 제공.

2. Pencil kit 사용하지 않고 애플 펜슬로 올가미툴도 복수선택 되도록 커스텀 개발 검토 부탁.

**Comment by Sungmin-Joo** [comment]
@jayleeee  
제가 저번 회의때 제가 헷갈리게 전달 드린 부분이 있는 것 같습니다.. (죄송합니당..)
- Pencil Kit에서 제공하는 올가미 툴을 사용하는 도구는 손이나 펜슬 상관 없이 다 가능하다.  
- 다만 Pencil Kit 에서 제공하는 올가미 툴을 사용 시 초기 주셨던 스펙들 구현에 이슈가 발생  
  - 텍스트라벨, 이미지를 같이 묶는건 어려움
  - 선택 후 크기 조절 어려움
  - 선택 후 노출되는 contextMenu 수정이 어려움  

이 상황이여서 사실 말씀해주신 1번 안을 적용하려면 올가미 툴을 자체 제작해야합니다.  

살짝 말씀해주셨던 방향을 정리해보면  
1. 기본 Pencil Kit으로 필기(그리기) 기능은 제공  
2. Pencil Kit으로 그린 그림들과 라벨, 이미지 등을 같이 선택할 수 있는 올가미 툴을 제작 가능할 지 검토  
3. 2번이 불가능하다면 아래 두 가지 안 중 한 가지 택하여 진행  
    - (1) Pencil Kit에서 제공하는 올가미 툴을 사용  
    - (2) Pencil Kit을 사용하지않고 그림 그리기 기능 부터 올가미 툴 까지 앱에 맞춰 직접 구현 (많은 공수가 들지만 기능은 다 될 것으로 예상)

**Comment by jayleeee** [comment]
아 나는 올가미툴에서 라벨,이미지 함께 묶는게 어려운 등의 한계가 있으니,
아예 1번으로 가면 올가미툴에서 Pencil을 제한하고 손으로만 하는게 낫겠다 판단한거였는데, 그렇게는 안된다는건가?

만약 그렇다면... Pencil Kit에서 제공하는 올가미툴 일단 사용하고 추 후에 3-2번으로 검토해봐야겠네.

**Comment by Sungmin-Joo** [comment]
@jayleeee  
> 만약 그렇다면... Pencil Kit에서 제공하는 올가미툴 일단 사용하고, (2번 검토해보고) 추후에 3-2번으로 검토해봐야겠네. 

넵 아마 이런 흐름으로 진행해야될 것 같습니다. 데모 버전으로 빠르게 작업해보고 결과물 보면서 검토해보는게 가장 좋을 것 같아요!
