### ISSUE TITLE
[QA] 홈/다이어리 (8월31일 배포 버전)

### ISSUE THREAD

**Issue by jayleeee** [Dayol-Studio/Dayol-iOS#259]
<테스트 환경>
기기 : iPhone 11 Pro
OS버전 : iOS 14.6
앱버전 : 1.0 (2021.831.2242)

![홈다이어리_0831](https://user-images.githubusercontent.com/23701517/132114008-d80e6011-c635-4580-a501-c33c2064b7a9.png)

**Comment by jayleeee** [comment]
지금 잠금설정 상태에서 비밀번호 아무거나 입력해도 막 들어가지던데, 암호틀렸을떄 case추가하고 암호도 정상작동하도록 수정바람!

**Comment by Sungmin-Joo** [comment]
![스크린샷 2021-09-03 오후 8 04 03](https://user-images.githubusercontent.com/46941349/131995620-1c9bf73e-8323-4674-8b57-6282e05bd394.png)

1. 작게 보이는 이유는 아마 사이즈 계산을 해봤을때 다이어리가 조금 잘려서 축소해서 보여줬던 것 같은데요 계산로직 한번 체크해보겠습니다.  
2. 크래시 나는 이유는 디비 문제이고 원인도 알아서, 다음 배포때 반영해보도록 하겠습니다.

**Comment by jayleeee** [comment]
홈/다이어리설정 부분 6,7번 추가함.

**Comment by jayleeee** [comment]
이슈 닫고 아직 수정안된것들은 개별적으로 재등록하겠음
