### ISSUE TITLE
[QA] 다이어리뷰, 먼슬리, 위클리  (8월 31일 배포버전)

### ISSUE THREAD

**Issue by jayleeee** [Dayol-Studio/Dayol-iOS#260]
<테스트 환경>
기기 : iPhone 11 Pro
OS버전 : iOS 14.6
앱버전 : 1.0 (2021.831.2242)

![다이어리뷰,먼슬,위클_0831](https://user-images.githubusercontent.com/23701517/132113989-55250088-6537-45d6-a450-6bffb451e516.png)

**Comment by ParkJongSang** [comment]
- [ ] 버튼 교체 가능, 버튼간격 수정(기술 검토)
- [ ] 하단 바 스와이프 불가능
- [ ] 액션시트 여백 조절 불가능: 시스템에 있는걸 활용, 없애는 것보단 별도의 Text를 사용하는 것을 권고
- [ ] 날짜표기법 변경 가능
- [ ] 페이지 > 이미지 저장 > 싱크 안맞음
- [ ] 속지 추가 버그, 중간에 생성됨
- [ ] 먼슬리 위클리 상단 헤더 터치영역 변경
- [ ] 날짜 생성 현재날짜 포커싱
- [ ] 속지 연결 버튼 Stroke 제거
- [ ] 속지 연결 > 속지 Add 시나리오 후 바로 연결시키기
- [ ] 위클리 하단 마진 제거
- [ ] 커스텀 데이트 피커 > 딤드된 숫자 터치시 월도 한번에 넘어가도록
- [ ] 일정상세 연결해제 > 팝업
- [ ] 일정상세 연결된 속지 Title <-> Content간 간격 확인
- [ ] 폰트 수정
- [ ] 일정 이름 없을 경우 "일정"으로 등록
- [ ] 일정 등록의 경우 바로 제목 포커싱되고 키보드 올라올 수 있도록
- [ ] 이미 있던 일정, 시간변경 데이터는 반영되나 뷰에 반영되지 않음

**Comment by jayleeee** [comment]
이슈 닫고 아직 수정안된것들은 개별적으로 재등록하겠음
