### ISSUE TITLE
텍스트 스타일 설정 모달 뷰 디자인 구현 이슈

### ISSUE THREAD

**Issue by Sungmin-Joo** [Dayol-Studio/Dayol-iOS#262]
<img width="773" alt="스크린샷 2021-09-04 오전 4 20 54" src="https://user-images.githubusercontent.com/46941349/132056350-6053ea68-f508-4ada-851e-76a9900af8eb.png">

위처럼 텍스트 필드를 edit하면서 계속 edit을 유지하고 싶은 경우, TextInputView 라는 속성에 뷰를 넣어줘야함.  

- 이슈 
  텍스트 뷰의 기본 백그라운드컬러가있어 라운드를 적용 시 기본 키보드 백그라운드가 살짝 보이는데, 해당 색상을 컨트롤하기가 어려움 
  (아직 방법을 찾지 못했지만 혹...시나 방법이 있을 수도 있으니 어렵다고 썼습니다.)   
  
<img width="422" alt="스크린샷 2021-09-04 오전 4 32 28" src="https://user-images.githubusercontent.com/46941349/132057335-20536410-a20c-4b33-8797-c009212379a9.png">

- 제안    
  라디우스를 없애고 기존 키보드처럼 디자인을 수정하는 방안  
  <img width="421" alt="스크린샷 2021-09-04 오전 4 35 54" src="https://user-images.githubusercontent.com/46941349/132057618-443c68d0-b6ee-458b-bb75-998a77f2bfa7.png">

**Comment by jayleeee** [comment]
radius 없이 가는거 이슈없슴다
