### ISSUE TITLE
[QA] 펜 컬러 기기에 저장

### ISSUE THREAD

**Issue by jayleeee** [Dayol-Studio/Dayol-iOS#270]
**AS IS**
사용자 커스텀 컬러 추가하고 현재 모달 닫으면 컬러 저장안되고 사라짐

**TO BE**
새로 펜 컬러를 등록한 경우 로컬 데이터에 저장했으면 함.

앱 껐다 켜도 저장되있도록.

![IMG_1443](https://user-images.githubusercontent.com/23701517/132130738-a7e503ab-4222-49d5-a1b8-38e753b7fcda.PNG)

**Comment by Sungmin-Joo** [comment]
다음 배포 부탁드립니다

**Comment by jayleeee** [comment]
모달 닫앗을때, 앱을 껐다켜도 유지되는거 확인
