### ISSUE TITLE
[QA] 사진/스티커 셀렉트박스 수정사항

### ISSUE THREAD

**Issue by jayleeee** [Dayol-Studio/Dayol-iOS#277]
- 사진/스티커 셀렉트박스
x버튼과 size 조정 버튼을 최신으로 교체해주세요.

- 사진 디폴트 크기
사진불러왔을때 첨에 너무 작게 뜨는데, 150pt로 해주세요.

![스크린샷 2021-09-11 오후 11 31 02](https://user-images.githubusercontent.com/23701517/132951334-bc62992d-1a9b-42fd-941c-71b5ebb7f05a.png)

**Comment by Sungmin-Joo** [comment]
다음 배포에서 확인 부탁드립니다
