### ISSUE TITLE
[스펙추가] 다이어리 생성 시 잠금 해제

### ISSUE THREAD

**Issue by jayleeee** [Dayol-Studio/Dayol-iOS#373]
베타테스터에서 의견나왔던건데 어렵지 않게 적용할 수 있을것 같아서 바로 가이드함.
알럿 띄우고 설정 해제시켜주면됨. 

![스크린샷 2021-10-07 오전 12 12 30](https://user-images.githubusercontent.com/23701517/136232078-38b543bb-6afe-4c5c-85f4-a38d5c64744f.png)

**Comment by ParkJongSang** [comment]
해당 기능 적용되어 닫습니다.
