### ISSUE TITLE
[QA] 속지 복제 시 오류사항들

### ISSUE THREAD

**Issue by jayleeee** [Dayol-Studio/Dayol-iOS#417]
1. 속지 복제 시 오브젝트들까지 정상적으로 복제가 되지 않고 있음.
2. 속지 복제 시 복제에 성공하더라도, 좌우 swipe해서 페이지 이동하니 해당 속지가 계속 반복되어 나타남; 닥터스트레인지처럼
3. 속지 복제 시 5장이 초과되어 광고를 보고 오는경우, 복제가 안되고 속지 추가 flow로 진입해버림.

**Comment by ParkJongSang** [comment]
2 번의 경우 인덱스가 꼬인 경우 같은데 간혹 삭제시에도 일어나고 있는 것으로 보입니다 ㅠㅠ 이부분은 심도 있게 확인해보겠습니다
