### ISSUE TITLE
[QA] 첫 시작시 홈에서 설정 안내가 들어가야함. 

### ISSUE THREAD

**Issue by jayleeee** [Dayol-Studio/Dayol-iOS#430]
영문은 'setting is here!'

앱 설치 시 최초 1번 뜨고, 클릭 하기 전까지 뜸

![스크린샷 2021-10-17 오전 12 14 55](https://user-images.githubusercontent.com/23701517/137593064-11b41a52-ec9f-47a4-a171-6c2489d74f55.png)

**Comment by ParkJongSang** [comment]
다음 버전에서 확인 부탁드립니다.
