### ISSUE TITLE
[QA] 커스텀 컬러 추가 시 목록의 맨 뒤가 아닌 앞으로 추가되도록 수정

### ISSUE THREAD

**Issue by jayleeee** [Dayol-Studio/Dayol-iOS#432]
텍스트 컬러, 펜 컬러에서 커스텀 컬러 추가시 현재 맨 뒤에 추가가 되는데, 맨 앞으로 추가되도록 수정

![스크린샷 2021-10-17 오전 1 01 19](https://user-images.githubusercontent.com/23701517/137594243-2739e727-e803-4f20-8930-070cf85b545a.png)

**Comment by Sungmin-Joo** [comment]
헷갈릴 수가 있으니 배포 되면 이슈 닫도록 하겠습니다
