### ISSUE TITLE
[QA] 드로잉 레이어 안내 이미지 교체

### ISSUE THREAD

**Issue by jayleeee** [Dayol-Studio/Dayol-iOS#434]
내용이 일부 수정되어서 이미지 교체만 부탁드림

![스크린샷 2021-10-17 오전 1 09 57](https://user-images.githubusercontent.com/23701517/137594526-52a041f8-c538-4bc7-a10c-22e60a4ff40b.png)

**Comment by Sungmin-Joo** [comment]
헷갈릴 수가 있으니 배포 되면 이슈 닫도록 하겠습니다
