### ISSUE TITLE
Date 관련 Localization  

### ISSUE THREAD

**Issue by Sungmin-Joo** [Dayol-Studio/Dayol-iOS#44]
https://www.wwdcnotes.com/notes/wwdc20/10160/  

wwdc2020보다가 발견한 내용인데요~ (위 링크는 정리된 노트)  

개발 과정에선 리터럴 문자열로 "Mon" 등을 표기하고 있는데, 나중에 localization 작업하면서 이 부분도 국가 표준에 맞게 가이드 맞춰두면 좋을 것 같아서 링크 남겨두겠습니다.

**Comment by ParkJongSang** [comment]
잘보겠습니다 ㅎㅎ
