### ISSUE TITLE
폰트 관련 이슈

### ISSUE THREAD

**Issue by Sungmin-Joo** [Dayol-Studio/Dayol-iOS#7]
- 이슈 내용
[#6] 번 PR 에서 비밀번호 입력 버튼에 사용될 폰트를 다운 받음  

- 확인 사항  
임시로 검색을 통해 폰트 리소스를 받아온 것 이기 때문에 앱 출시 전 라이센스 관련 확인이 필요  

이 외에도 폰트 관련 이슈가 생기면 코멘트로 히스토리 남긴 뒤,
폰트를 한번에 구매하거나 라이센스를 명시하는 등의 작업이 필요할 것으로 예상됩니다.

**Comment by jayleeee** [comment]
폰트는 오픈라이센스(배포까지 가능한 폰트)만 사용할거구, 내가 취합해서 전달해줄께.
한글 폰트, 영문 폰트 일단 2개만 지원할거구.
언어설정으로 한글인경우는 한글폰트만 노출되고, 그 외 국가는 영문폰트 지원되는것으로 하면될것 같아.
