### ISSUE TITLE
Pencil Kit 이슈 정리

### ISSUE THREAD

**Issue by Sungmin-Joo** [Dayol-Studio/Dayol-iOS#93]
apple pencil kit 이슈  

## 지우개  
- 지우개 사이즈 선택이 안됨 

## 아이폰에서 드로잉 인터랙션  
- 속지 스크롤, 인터랙션과 과 드로잉 인터랙션이 겹쳐서 룰을 정해할필요가 있음
    - 1. 단순하게 아이폰에서는 드로잉 기능 사용 불가 
    - 2. 애플 메모처럼 드로잉(펜, 지우개, 올가미) 동작을 진행할땐 스크롤과 관련된 인터랙션을 막고, 드로잉 동작이 완료되면 다시 스크롤 인터랙션을 가능하게 함.  
    - 3. 다이어리 생성, 편집화면 / 속지 편집 화면 드로잉 툴(펜, 지우개, 올가미)를 폰에서 사용 시 두손가락으로 스크롤, 한 손가락은 드로인 도구의 기능 수행하도록  
        - > 3번에서 두손가락 스크롤을 구현해 본 적이 없는데 3번 관련해서 기술조사도 필요할 것 같습니다.

2번 방법 적용 시 애플 메모 참고 예시  

￼<img src = "https://user-images.githubusercontent.com/46941349/116687366-01a88a80-a9f0-11eb-97ea-5e79aa8b7b85.png" width = 300> <img src = "https://user-images.githubusercontent.com/46941349/116687398-1127d380-a9f0-11eb-93cd-21287188d647.png" width = 300>

**Comment by jayleeee** [comment]
올가미툴은 사진이랑 스티커 필수로 되야됌 ㅜ.ㅜ 커스텀 검토부탁함

**Comment by Sungmin-Joo** [comment]
# 라이브러리 조사  

## NXDrawKit - https://github.com/Nicejinux/NXDrawKit
<img src="https://user-images.githubusercontent.com/46941349/124593601-cc119900-de99-11eb-8909-b29b9e238d74.png" width = 300>
- 정말 드로우 기능만 있음 (올가미는 없고 형광팬은 색의 알파값을 조절해서 구현해야할 듯)
- 필기감 나쁘지 않음
- 지우개 기능조차도 구현해야함   

## Drawsana - https://github.com/Asana/Drawsana
<img src="https://user-images.githubusercontent.com/46941349/124593917-2874b880-de9a-11eb-9e0d-4d6f0775c29b.png" width = 300>
- 드로잉, 지우개, 직선, 셀렉션(올가미는 아니고 개별 선택 및 이동) 등 다양한 기능 지원 
- 필기감이 매우 나쁨  

## SwiftyDraw - https://github.com/Awalz/SwiftyDraw
<img src="https://user-images.githubusercontent.com/46941349/124594409-b94b9400-de9a-11eb-935f-ca2e3c45d4bf.png" width = 300>
- 조사한 라이브러리 중 필기감 가장 좋음  
- 18년도에 fps드랍 이슈가 있는데 아직 해결이안된건지 close가 안됨  
- 드로잉, 지우개, 사각형, 원 등 기능 있음
- 언두 리두 있음 구현 되어있음

## 공통
- 오브젝트 지우개 없음
- 올가미 없음
